AccessorMethodName:
  Enabled: false

GuardClause:
  Enabled: false

StringLiterals:
  Enabled: false

BracesAroundHashParameters:
  Enabled: false

SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

SpaceInsideHashLiteralBraces:
  Enabled: false

SingleSpaceBeforeFirstArg:
  Enabled: false

HashSyntax:
  EnforcedStyle: hash_rockets

ClassLength:
  Max: 112

ColonMethodCall:
  Enabled: false

Documentation:
  Enabled: false

EmptyLinesAroundBody:
  Enabled: false

# FavorUnlessOverNegatedIf:
  # Enabled: false

IfUnlessModifier:
  Enabled: false

LineLength:
  Max: 160

Loop:
  Enabled: true

MethodCallParentheses:
  Enabled: false

MethodLength:
  Max: 23

NilComparison:
  Enabled: false

ParenthesesAroundCondition:
  Enabled: false

RedundantSelf:
  Enabled: false

SignalException:
  EnforcedStyle: only_raise

TrivialAccessors:
  Enabled: false

Void:
  Enabled: false

WordArray:
  Enabled: false

AsciiIdentifiers:
  Enabled: false

AsciiComments:
  Enabled: false
