require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PostcodesController do

  # This should return the minimal set of attributes required to create a valid
  # Postcode. As you add validations to Postcode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "postcode" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostcodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all postcodes as @postcodes" do
      postcode = Postcode.create! valid_attributes
      get :index, {}, valid_session
      assigns(:postcodes).should eq([postcode])
    end
  end

  describe "GET show" do
    it "assigns the requested postcode as @postcode" do
      postcode = Postcode.create! valid_attributes
      get :show, {:id => postcode.to_param}, valid_session
      assigns(:postcode).should eq(postcode)
    end
  end

  describe "GET new" do
    it "assigns a new postcode as @postcode" do
      get :new, {}, valid_session
      assigns(:postcode).should be_a_new(Postcode)
    end
  end

  describe "GET edit" do
    it "assigns the requested postcode as @postcode" do
      postcode = Postcode.create! valid_attributes
      get :edit, {:id => postcode.to_param}, valid_session
      assigns(:postcode).should eq(postcode)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Postcode" do
        expect {
          post :create, {:postcode => valid_attributes}, valid_session
        }.to change(Postcode, :count).by(1)
      end

      it "assigns a newly created postcode as @postcode" do
        post :create, {:postcode => valid_attributes}, valid_session
        assigns(:postcode).should be_a(Postcode)
        assigns(:postcode).should be_persisted
      end

      it "redirects to the created postcode" do
        post :create, {:postcode => valid_attributes}, valid_session
        response.should redirect_to(Postcode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved postcode as @postcode" do
        # Trigger the behavior that occurs when invalid params are submitted
        Postcode.any_instance.stub(:save).and_return(false)
        post :create, {:postcode => { "postcode" => "invalid value" }}, valid_session
        assigns(:postcode).should be_a_new(Postcode)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Postcode.any_instance.stub(:save).and_return(false)
        post :create, {:postcode => { "postcode" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested postcode" do
        postcode = Postcode.create! valid_attributes
        # Assuming there are no other postcodes in the database, this
        # specifies that the Postcode created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Postcode.any_instance.should_receive(:update).with({ "postcode" => "1" })
        put :update, {:id => postcode.to_param, :postcode => { "postcode" => "1" }}, valid_session
      end

      it "assigns the requested postcode as @postcode" do
        postcode = Postcode.create! valid_attributes
        put :update, {:id => postcode.to_param, :postcode => valid_attributes}, valid_session
        assigns(:postcode).should eq(postcode)
      end

      it "redirects to the postcode" do
        postcode = Postcode.create! valid_attributes
        put :update, {:id => postcode.to_param, :postcode => valid_attributes}, valid_session
        response.should redirect_to(postcode)
      end
    end

    describe "with invalid params" do
      it "assigns the postcode as @postcode" do
        postcode = Postcode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Postcode.any_instance.stub(:save).and_return(false)
        put :update, {:id => postcode.to_param, :postcode => { "postcode" => "invalid value" }}, valid_session
        assigns(:postcode).should eq(postcode)
      end

      it "re-renders the 'edit' template" do
        postcode = Postcode.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Postcode.any_instance.stub(:save).and_return(false)
        put :update, {:id => postcode.to_param, :postcode => { "postcode" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested postcode" do
      postcode = Postcode.create! valid_attributes
      expect {
        delete :destroy, {:id => postcode.to_param}, valid_session
      }.to change(Postcode, :count).by(-1)
    end

    it "redirects to the postcodes list" do
      postcode = Postcode.create! valid_attributes
      delete :destroy, {:id => postcode.to_param}, valid_session
      response.should redirect_to(postcodes_url)
    end
  end

end
